version: '3.8'

services:
  db:
    image: postgres:15
    container_name: naseeb-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: naseeb-app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - naseeb-net

volumes:
  postgres_data:

networks:
  naseeb-net:
    driver: bridge
